feat: New "Mapeo for ICCAs" variant for UNEP WCMC (#346)
* feat: Add intro screens for ICCA / WCMC

* feat: Add icca presets for icca app flavor

* feat: Only show icca intro screens for icca build flavor

* feat: Add ICCA splash screen and logo

* chore: package-lock updates

* Build ICCA for beta

* fix package-lock

* remove unused dep

* add signing config for mapeo for iccas

* fix S3 upload and ignore failed S3 uploads in the future

* Include ICCA variant in S3 release & beta uploads

* Update download URLs to point to latest release

* Fix syntax error in APK path names

* [skip ci] fix script location

* Fix path for google play upload

* debug source_dir

* Fix - change working dir after gradle build

* Another fix for scripts :/

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -25,27 +25,55 @@ workflows:
     before_run:
       - primary
     envs:
-      - GRADLE_TASKS: assembleQaUniversal assembleAppUniversal
+      - GRADLE_TASKS: assembleQaUniversal assembleAppUniversal assembleIccaUniversal
         opts:
           is_expand: false
     steps:
+      - script@1.1.6:
+          title: Set APK path variables
+          inputs:
+            - content: |-
+                #!/usr/bin/env bash
+                # fail if any commands fails
+                set -e
+                # debug log
+                set -x
+
+                UNIVERSAL_APK_PATH=$(echo -n "${BITRISE_APK_PATH_LIST//|/$'\n'}" | grep mapeo-universal)
+                QA_UNIVERSAL_APK_PATH=$(echo -n "${BITRISE_APK_PATH_LIST//|/$'\n'}" | grep mapeo-QA-universal)
+                ICCA_UNIVERSAL_APK_PATH=$(echo -n "${BITRISE_APK_PATH_LIST//|/$'\n'}" | grep mapeo-ICCA-universal)
+
+                envman add --key UNIVERSAL_APK_PATH --value "$UNIVERSAL_APK_PATH"
+                envman add --key QA_UNIVERSAL_APK_PATH --value "$QA_UNIVERSAL_APK_PATH"
+                envman add --key ICCA_UNIVERSAL_APK_PATH --value "$ICCA_UNIVERSAL_APK_PATH"
       - deploy-to-bitrise-io@1.9.5: {}
       - amazon-s3-uploader@1.0.1:
           title: Upload QA variant
+          is_skippable: true
           inputs:
             - aws_access_key: $AWS_ACCESS_KEY_ID
             - aws_secret_key: $AWS_SECRET_ACCESS_KEY
             - bucket_name: mapeo-apks
-            - path_in_bucket: beta-testing/qa
-            - file_path: ${BITRISE_DEPLOY_DIR}/mapeo-qa-universal-${ANDROID_VERSION_NAME}-qa.apk
+            - path_in_bucket: beta-testing/v${VERSION_NAME}
+            - file_path: $QA_UNIVERSAL_APK_PATH
       - amazon-s3-uploader@1.0.1:
           title: Upload Release variant
+          is_skippable: true
           inputs:
             - aws_access_key: $AWS_ACCESS_KEY_ID
             - aws_secret_key: $AWS_SECRET_ACCESS_KEY
             - bucket_name: mapeo-apks
-            - path_in_bucket: beta-testing/default
-            - file_path: ${BITRISE_DEPLOY_DIR}/mapeo-universal-${ANDROID_VERSION_NAME}.apk
+            - path_in_bucket: beta-testing/v${VERSION_NAME}
+            - file_path: $UNIVERSAL_APK_PATH
+      - amazon-s3-uploader@1.0.1:
+          title: Upload ICCA variant
+          is_skippable: true
+          inputs:
+            - aws_access_key: $AWS_ACCESS_KEY_ID
+            - aws_secret_key: $AWS_SECRET_ACCESS_KEY
+            - bucket_name: mapeo-apks
+            - path_in_bucket: beta-testing/v${VERSION_NAME}
+            - file_path: $ICCA_UNIVERSAL_APK_PATH
     meta:
       bitrise.io: null
       stack: linux-docker-android
@@ -84,11 +112,11 @@ workflows:
       bitrise.io: null
       stack: linux-docker-android
   deploy-release:
-    description: Deploy for QA testing
+    description: Deploy release builds
     before_run:
       - primary
     envs:
-      - GRADLE_TASKS: assembleApp bundleAppUniversal -x assembleAppDebug
+      - GRADLE_TASKS: assembleApp assembleIccaRelease bundleAppUniversal -x assembleAppDebug
         opts:
           is_expand: false
     steps:
@@ -103,28 +131,42 @@ workflows:
                 # debug log
                 set -x
 
+                echo "SOURCE_DIR = ${BITRISE_SOURCE_DIR}"
+
                 RELEASE_APK_PATH=$(echo -n "${BITRISE_APK_PATH_LIST//|/$'\n'}" | grep mapeo-v)
                 INTEL_APK_PATH=$(echo -n "${BITRISE_APK_PATH_LIST//|/$'\n'}" | grep mapeo-intel)
                 UNIVERSAL_APK_PATH=$(echo -n "${BITRISE_APK_PATH_LIST//|/$'\n'}" | grep mapeo-universal)
+                ICCA_RELEASE_APK_PATH=$(echo -n "${BITRISE_APK_PATH_LIST//|/$'\n'}" | grep mapeo-ICCA)
 
-                envman --key RELEASE_APK_PATH --value "$RELEASE_APK_PATH"
-                envman --key INTEL_APK_PATH --value "$INTEL_APK_PATH"
-                envman --key UNIVERSAL_APK_PATH --value "$UNIVERSAL_APK_PATH"
+                envman add --key RELEASE_APK_PATH --value "$RELEASE_APK_PATH"
+                envman add --key INTEL_APK_PATH --value "$INTEL_APK_PATH"
+                envman add --key UNIVERSAL_APK_PATH --value "$UNIVERSAL_APK_PATH"
+                envman add --key ICCA_RELEASE_APK_PATH --value "$ICCA_RELEASE_APK_PATH"
       - amazon-s3-uploader@1.0.1:
           title: Upload APK for Arm
           inputs:
             - aws_access_key: $AWS_ACCESS_KEY_ID
             - aws_secret_key: $AWS_SECRET_ACCESS_KEY
             - bucket_name: mapeo-apks
-            - path_in_bucket: beta-testing/qa
+            - path_in_bucket: release/${VERSION_NAME}
             - file_path: $RELEASE_APK_PATH
+      - script@1.1.6:
+          inputs:
+            - content: |-
+                #!/usr/bin/env bash
+                # fail if any commands fails
+                set -e
+                # debug log
+                set -x
+
+                node ./scripts/gh-pages-redirect.js /icca/latest https://mapeo-apks.s3.amazonaws.com/release/${VERSION_NAME}/${RELEASE_APK_PATH##*/}
       - amazon-s3-uploader@1.0.1:
           title: Upload APK for x86
           inputs:
             - aws_access_key: $AWS_ACCESS_KEY_ID
             - aws_secret_key: $AWS_SECRET_ACCESS_KEY
             - bucket_name: mapeo-apks
-            - path_in_bucket: beta-testing/default
+            - path_in_bucket: release/${VERSION_NAME}
             - file_path: $INTEL_APK_PATH
       - amazon-s3-uploader@1.0.1:
           title: Upload universal (all ABIs) APK
@@ -132,8 +174,20 @@ workflows:
             - aws_access_key: $AWS_ACCESS_KEY_ID
             - aws_secret_key: $AWS_SECRET_ACCESS_KEY
             - bucket_name: mapeo-apks
-            - path_in_bucket: beta-testing/default
+            - path_in_bucket: release/${VERSION_NAME}
             - file_path: $UNIVERSAL_APK_PATH
+      - amazon-s3-uploader@1.0.1:
+          title: Upload APK for ICCA (Arm)
+          inputs:
+            - aws_access_key: $AWS_ACCESS_KEY_ID
+            - aws_secret_key: $AWS_SECRET_ACCESS_KEY
+            - bucket_name: mapeo-apks
+            - path_in_bucket: release-ICCA/${VERSION_NAME}
+            - file_path: $ICCA_RELEASE_APK_PATH
+      - script-runner@0.9.3:
+          title: Update download URL for ICCA release
+          inputs:
+            - file_path: scripts/gh-pages-redirect.js /icca/latest https://mapeo-apks.s3.amazonaws.com/release/${VERSION_NAME}/${ICCA_RELEASE_APK_PATH##*/}
       - script@1.1.6:
           title: Generate release description
           inputs:
@@ -161,7 +215,7 @@ workflows:
             - service_account_json_key_path: $BITRISEIO_SERVICE_ACCOUNT_JSON_KEY_URL
             - track: beta
             - apk_path: $RELEASE_APK_PATH
-            - app_path: ${BITRISE_SOURCE_DIR}/app.aab
+            - app_path: ${BITRISE_DEPLOY_DIR}/app.aab
             - package_name: com.mapeo
     meta:
       bitrise.io: null
@@ -286,6 +340,10 @@ workflows:
                 *Test*.apk
                 mapeo-debug*.apk
             - gradle_task: $GRADLE_TASKS
+      - change-workdir@1.0.2:
+          inputs:
+            - is_create_path: "false"
+            - path: ..
     meta:
       bitrise.io: null
       stack: linux-docker-android
